
version: '3.8'

services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build:
      context: ./producer-mc1-part2
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - rabbitmq
    ports:
      - 7000:7000

  receiver:
    build:
      context: ./receiver-mc1-part2
      dockerfile: Dockerfile
    container_name: receiver
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq


